name: Build UniversalHookX

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository (with Submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are cloned

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build with MSBuild
        run: msbuild UniversalHookX.sln /p:Configuration=Release /p:Platform=x64

      - name: Find Generated Files (Debug Step)
        run: dir /s /b > file_list.txt

      - name: Upload File List (Debug)
        uses: actions/upload-artifact@v4
        with:
          name: Debug-File-List
          path: file_list.txt

      - name: Upload Artifacts (Final DLLs)
        uses: actions/upload-artifact@v4
        with:
          name: UniversalHookX-DLL
          path: "**/*.dll"
