name: Build UniversalHookX

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository (with Submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensures submodules are cloned

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build with MSBuild
        run: msbuild UniversalHookX.sln /p:Configuration=Release /p:Platform=x64

      - name: Debug Find Generated Files
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse | Select-Object FullName | Out-File file_list.txt

      - name: Upload File List (Debugging)
        uses: actions/upload-artifact@v4
        with:
          name: Debug-File-List
          path: file_list.txt

      - name: Upload DLLs (Final Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: UniversalHookX-DLL
          path: "**/*.dll"
